services:
  userandunitmanagement.api:
    image: ${DOCKER_REGISTRY-}userandunitmanagementapi
    build:
      context: .
      dockerfile: UserAndUnitManagement.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=db;Database=UserAndUnitManagement;User=sa;Password=yourStrong(!)Password;Trusted_Connection=False;Encrypt=False"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"