version: '3.8'
networks:
  internal_network:
    driver: bridge

services:
  communityconnect-userandunitmgmtapi-dev:
    image: ${DOCKER_REGISTRY-}communityconnectuserandunitmgmtapi
    build:
      context: UserAndUnitManagement
      dockerfile: UserAndUnitManagement.Api/UserAndUnitManagement.Api.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
      - "ConnectionStrings:DefaultConnection=Server=communityconnect-db-dev;Database=UserAndUnitManagementDb;User Id=sa;Password=5Tmb-_zJryCV)yLv)NNw;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=True;Integrated Security=False"
    volumes:
      - .:/src
    depends_on:
      communityconnect-db-dev:
        condition: service_healthy
    profiles: ["development"]
    entrypoint: ["dotnet", "UserAndUnitManagement.Api.dll"]
    command: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "8081:8081"
    restart: on-failure
    networks:
      - internal_network

  communityconnect-communicationhub-api-dev:
    image: ${DOCKER_REGISTRY-}communityconnectcommunicationhubapi
    build:
      context: CommunicationHub
      dockerfile: CommunicationHub.Api/CommunicationHub.Api.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8082
      - "ConnectionStrings:DefaultConnection=Server=communityconnect-db-dev;Database=CommunicationHubDb;User Id=sa;Password=5Tmb-_zJryCV)yLv)NNw;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=True;Integrated Security=False"
      - JWTSETTINGS__SECRET=a-very-long-and-super-secret-key-for-development
    volumes:
      - .:/src
    depends_on:
      communityconnect-db-dev:
        condition: service_healthy
    profiles: ["development"]
    entrypoint: ["dotnet", "CommunicationHub.Api.dll"]
    command: []
    ports:
      - "8082:8082"
    restart: on-failure
    networks:
      - internal_network

  communityconnect-maintenanceservice-api-dev:
    image: ${DOCKER_REGISTRY-}communityconnectmaintenanceserviceapi
    build:
      context: MaintenanceService
      dockerfile: MaintenanceService.Api/MaintenanceService.Api.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8083
      - "ConnectionStrings:MaintenanceDbConnection=Server=communityconnect-db-dev;Database=MaintenanceDb;User Id=sa;Password=5Tmb-_zJryCV)yLv)NNw;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=True;Integrated Security=False"
    volumes:
      - .:/src
    depends_on:
      communityconnect-db-dev:
        condition: service_healthy
    profiles: ["development"]
    entrypoint: ["dotnet", "MaintenanceService.Api.dll"]
    command: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "8083:8083"
    restart: on-failure
    networks:
      - internal_network

  communityconnect-financeservice-api-dev:
    image: ${DOCKER_REGISTRY-}communityconnectfinanceserviceapi
    build:
      context: FinanceService
      dockerfile: FinanceService.Api/FinanceService.Api.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8084
      - "ConnectionStrings:DefaultConnection=Server=communityconnect-db-dev;Database=FinanceServiceDb;User Id=sa;Password=5Tmb-_zJryCV)yLv)NNw;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=True;Integrated Security=False"
    volumes:
      - .:/src
    depends_on:
      communityconnect-db-dev:
        condition: service_healthy
    profiles: ["development"]
    entrypoint: ["dotnet", "FinanceService.Api.dll"]
    command: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "8084:8084"
    restart: on-failure
    networks:
      - internal_network

  communityconnect-gateway-dev:
    image: ${DOCKER_REGISTRY-}communityconnect-gateway
    build:
      context: Gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      communityconnect-userandunitmgmtapi-dev:
        condition: service_healthy
      communityconnect-communicationhub-api-dev:
        condition: service_healthy
      communityconnect-maintenanceservice-api-dev:
        condition: service_healthy # Add dependency for the new service
      communityconnect-financeservice-api-dev:
        condition: service_healthy
    profiles: ["development"]
    networks:
      - internal_network
    restart: on-failure

  communityconnect-db-dev:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: '5Tmb-_zJryCV)yLv)NNw'
      ACCEPT_EULA: 'Y'
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "5Tmb-_zJryCV)yLv)NNw", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    profiles: ["development"]
    networks:
      - internal_network
    restart: on-failure

  communityconnect-userandunitmgmtapi-staging:
    image: ${DOCKER_REGISTRY-}communityconnectuserandunitmgmtapi
    build:
      context: UserAndUnitManagement
      dockerfile: UserAndUnitManagement.Api/UserAndUnitManagement.Api.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:8080
      - "ConnectionStrings:DefaultConnection=Server=communityconnect-db-staging;Database=UserAndUnitManagementDbStaging;User Id=sa;Password=5Tmb-_zJryCV)yLv)NNw;MultipleActiveResultSets=true;TrustServerCertificate=True"
      - JWTSETTINGS__SECRET=a-very-long-and-super-secret-key-for-staging
    depends_on:
      communityconnect-db-staging:
        condition: service_healthy
    profiles: ["staging"]
    restart: on-failure
    networks:
      - internal_network

  communityconnect-db-staging:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: '5Tmb-_zJryCV)yLv)NNw'
      ACCEPT_EULA: 'Y'
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "5Tmb-_zJryCV)yLv)NNw", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    profiles: ["staging"]
    restart: on-failure
    networks:
      - internal_network

  communityconnect-userandunitmgmtapi-prod:
    image: ${DOCKER_REGISTRY-}communityconnectuserandunitmgmtapi
    build:
      context: UserAndUnitManagement
      dockerfile: UserAndUnitManagement.Api/UserAndUnitManagement.Api.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - "ConnectionStrings:DefaultConnection=Server=communityconnect-db-prod;Database=UserAndUnitManagementDbProduction;User Id=sa;Password=5Tmb-_zJryCV)yLv)NNw;MultipleActiveResultSets=true;TrustServerCertificate=True"
      - JWTSETTINGS__SECRET=a-very-long-and-super-secret-key-for-production
    depends_on:
      communityconnect-db-prod:
        condition: service_healthy
    profiles: ["production"]
    restart: on-failure
    networks:
      - internal_network

  communityconnect-db-prod:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: '5Tmb-_zJryCV)yLv)NNw'
      ACCEPT_EULA: 'Y'
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "5Tmb-_zJryCV)yLv)NNw", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    profiles: ["production"]
    restart: on-failure
    networks:
      - internal_network
